config/routes.rb
Rails.application.routes.draw do
 
  resources :image_uploaders
  resources :users
  resources :images do
    collection do 
      get 'search_image'
    end
  end
  resources :photos do
    get 'without_member', to: 'photos#without_member                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '
    get 'preview', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image_uploader.rb
class ImageUploader < ApplicationRecord
  has_one_attached :avatar_image
end

app/controllers/image_uploaders_controller.rb
class ImageUploadersController < ApplicationController
  before_action :set_image_uploader, only: [:show, :edit, :update, :destroy]

  # GET /image_uploaders
  # GET /image_uploaders.json
  def index
    @image_uploaders = ImageUploader.all
  end

  # GET /image_uploaders/1
  # GET /image_uploaders/1.json
  def show
  end

  # GET /image_uploaders/new
  def new
    @image_uploader = ImageUploader.new
  end

  # GET /image_uploaders/1/edit
  def edit
  end

  # POST /image_uploaders
  # POST /image_uploaders.json
  def create
    @image_uploader = ImageUploader.new(image_uploader_params)
    @image_uploader.avatar_image.attach(params[:avatar_image])
    respond_to do |format|
      if @image_uploader.save
        format.html { redirect_to @image_uploader, notice: 'Image uploader was successfully created.' }
        format.json { render :show, status: :created, location: @image_uploader }
      else
        format.html { render :new }
        format.json { render json: @image_uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_uploaders/1
  # PATCH/PUT /image_uploaders/1.json
  def update
    respond_to do |format|
      if @image_uploader.update(image_uploader_params)
        format.html { redirect_to @image_uploader, notice: 'Image uploader was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_uploader }
      else
        format.html { render :edit }
        format.json { render json: @image_uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_uploaders/1
  # DELETE /image_uploaders/1.json
  def destroy
    @image_uploader.destroy
    respond_to do |format|
      format.html { redirect_to image_uploaders_url, notice: 'Image uploader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_uploader
      @image_uploader = ImageUploader.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_uploader_params
      params.require(:image_uploader).permit(:name, :email, :avtar, :avatar_image)
    end
end

app/helpers/image_uploaders_helper.rb
module ImageUploadersHelper
end

app/views/image_uploaders/_form.html.erb
<%= form_with(model: image_uploader, local: true) do |form| %>
  <% if image_uploader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_uploader.errors.count, "error") %> prohibited this image_uploader from being saved:</h2>

      <ul>
        <% image_uploader.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avtar_image %>
    <%= form.file_field :avatar_image %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :avtar %>
    <%= form.text_field :avtar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/image_uploaders/edit.html.erb
<h1>Editing Image Uploader</h1>

<%= render 'form', image_uploader: @image_uploader %>

<%= link_to 'Show', @image_uploader %> |
<%= link_to 'Back', image_uploaders_path %>

app/views/image_uploaders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Uploaders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Avtar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_uploaders.each do |image_uploader| %>
      <tr>
        <td><%= image_uploader.name %></td>
        <td><%= image_uploader.email %></td>
        <td><%= image_uploader.avtar %></td>
        <td><%= link_to 'Show', image_uploader %></td>
        <td><%= link_to 'Edit', edit_image_uploader_path(image_uploader) %></td>
        <td><%= link_to 'Destroy', image_uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Uploader', new_image_uploader_path %>

app/views/image_uploaders/new.html.erb
<h1>New Image Uploader</h1>

<%= render 'form', image_uploader: @image_uploader %>

<%= link_to 'Back', image_uploaders_path %>

app/views/image_uploaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image_uploader.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @image_uploader.email %>
</p>

<p>
  <strong>Avtar:</strong>
  <%= @image_uploader.avtar %>
</p>

<%= link_to 'Edit', edit_image_uploader_path(@image_uploader) %> |
<%= link_to 'Back', image_uploaders_path %>